# Members area (/members/*). Gated by netlify/edge-functions/members (login required),
# except /members/login/. All pages noindex and kept out of the sitemap and nav.
# Executed from build.py after coaching.py, so head(), topbar(), FOOT, write(), html, NOINDEX, COACHCSS are in scope.

# Supabase public project settings (safe to publish: the anon/publishable key only allows what auth rules permit).
SBCFG = f"window.SB = {json.dumps({'url': SB_URL, 'key': SB_KEY})};\n"
open(os.path.join(ROOT, "assets", "sb-config.js"), "w").write("// Generated by tools/build.py from content.py (SB_URL, SB_KEY).\n" + SBCFG)
open(os.path.join(ROOT, "netlify", "edge-functions", "members", "config.ts"), "w").write(
    "// Generated by tools/build.py from content.py. Public values.\n" + f"export const SB_URL = {json.dumps(SB_URL)};\nexport const SB_KEY = {json.dumps(SB_KEY)};\n")

AUTHJS = '  <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>\n  <script src="/assets/sb-config.js"></script>\n  <script src="/assets/auth.js"></script>\n'

MCSS = """<style>
.mb{padding-top:36px}
.mb-top{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}
.mb-top .who{color:var(--faint);font-size:14px}
.mb-top button{background:none;border:1px solid var(--rule);color:var(--dim);border-radius:99px;padding:8px 14px;font:600 13px Inter,sans-serif;cursor:pointer}
.mb h1{font-size:clamp(32px,6vw,52px);margin:10px 0 0}
.mb-nav{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0 0}
.mb-nav a{padding:9px 14px;border:1px solid var(--rule);border-radius:99px;color:var(--fg);text-decoration:none;font-weight:600;font-size:14px}
.mb-nav a[aria-current]{border-color:var(--rust);background:rgba(190,81,38,.14)}
.mb-tiles{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:18px 0 0;max-width:640px}
.mb-tiles div{background:var(--raised);border:1px solid var(--rule);border-radius:12px;padding:12px 14px}
.mb-tiles .hl{grid-column:span 3;border-color:var(--rust);background:rgba(190,81,38,.12)}
.mb-tiles b{display:block;font-family:Oswald,sans-serif;font-size:26px;line-height:1.1}
.mb-tiles .hl b{font-size:40px;color:var(--rust-text)}
.mb-tiles span{color:var(--faint);font-size:12px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase}
.mb-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px;margin:22px 0 0}
.mb-cards a{display:block;background:var(--raised);border:1px solid var(--rule);border-radius:14px;padding:18px;text-decoration:none;color:var(--fg);transition:border-color .15s}
.mb-cards a:hover{border-color:var(--rust)}
.mb-cards small{color:var(--rust-text);font-size:11.5px;font-weight:700;letter-spacing:2px;text-transform:uppercase}
.mb-cards b{display:block;font-family:Oswald,sans-serif;text-transform:uppercase;font-size:21px;margin:4px 0}
.mb-cards span{color:var(--dim);font-size:14.5px}
.mb-sec{margin:44px 0 0}
.mb-sec h2{font-family:Oswald,sans-serif;text-transform:uppercase;font-size:clamp(24px,4vw,32px);margin:0 0 10px;letter-spacing:.3px}
.mb-sec h3{font-size:17px;margin:22px 0 6px}
.mb-sec p,.mb-sec li{color:var(--dim);font-size:16px}
.mb-sec ul{padding-left:20px}
.mb-sec li{margin:6px 0}
.mb-sec li::marker{color:var(--rust)}
.mb-sec li b{color:var(--fg)}
.mb-box{background:var(--raised);border:1px solid var(--rule);border-left:3px solid var(--rust);border-radius:12px;padding:16px 18px;margin:18px 0 0}
.mb-box p{margin:0 0 8px;font-size:15px}.mb-box p:last-child{margin:0}
.mb-disc{color:var(--faint);font-size:13.5px;border-top:1px solid var(--rule);padding-top:16px;margin:44px 0 0}
.mb-login{max-width:480px;margin:0 auto;padding:56px 0 0}
.mb-login form{display:grid;gap:10px;margin:22px 0 0}
.mb-login input{min-height:52px;padding:12px 16px;border-radius:10px;border:1px solid var(--rule);background:var(--raised);color:var(--fg);font:inherit;font-size:16px}
.mb-login button{border:0;cursor:pointer;font-family:Inter,sans-serif}
.mb-msg{margin:16px 0 0;padding:14px 16px;border-radius:12px;background:var(--raised);border:1px solid var(--rule);color:var(--dim)}
.mb-msg.ok{border-color:#3c7a4f}.mb-msg.err{border-color:var(--rust)}
</style>
"""

def mnav(cur):
    items = [("/members/", "Dashboard", "home"), ("/members/bloodwork/", "Bloodwork guide", "labs"), ("/members/peptides/", "Peptides 101", "pep")]
    return '<nav class="mb-nav" aria-label="Members">' + "".join(
        f'<a href="{h}"{" aria-current=page" if k == cur else ""}>{t}</a>' for h, t, k in items) + "</nav>"

def mtop():
    return '<div class="mb-top"><p class="eyebrow" style="margin:0">Members</p><span class="who"><span id="mb-who"></span> <button type="button" onclick="SH_AUTH.signOut()">Log out</button></span></div>'

MEMBERJS = """  <script>
  SH_AUTH.session().then(function (s) {
    if (!s) { location.replace('/members/login/?next=' + encodeURIComponent(location.pathname)); return; }
    var u = s.user || {}, m = u.user_metadata || {}, w = document.getElementById('mb-who'); if (w) w.textContent = u.email || '';
    var pend = null; try { pend = JSON.parse(localStorage.getItem('sh-qz') || 'null'); } catch (e) {}
    if (pend && (!m.qualified_at || pend.qualified_at > m.qualified_at)) { SH_AUTH.saveProfile(pend).then(function (ok) { if (ok) try { localStorage.removeItem('sh-qz'); } catch (e) {} }); for (var k in pend) m[k] = pend[k]; }
    else if (pend) try { localStorage.removeItem('sh-qz'); } catch (e) {}
    if (window.mbFill) window.mbFill(m, u);
  });
  </script>
"""

# ---- login -----------------------------------------------------------------
lp = head("Member login | Salvage Health", "Log in to the Salvage Health members area.", "/members/login/", NOINDEX + COACHCSS + MCSS) + topbar("members") + """  <main class="co">
    <div class="mb-login">
      <p class="eyebrow">Members</p>
      <h1 class="disp" style="font-size:clamp(34px,7vw,52px)">Member <em>login</em></h1>
      <p class="dek" id="mb-intro">Enter your email and I'll send you a one-tap login link. No password to remember.</p>
      <form id="mb-form">
        <label class="sr" for="mb-email">Email address</label>
        <input id="mb-email" type="email" required autocomplete="email" placeholder="Your email address">
        <button class="btn solid" type="submit">Email me a login link</button>
      </form>
      <div id="mb-out" class="mb-msg" hidden></div>
      <p style="color:var(--faint);font-size:14px;margin:22px 0 0">Not a member yet? Membership is free when you complete the <a href="/coaching/qualify/">coaching questionnaire</a>.</p>
    </div>
  </main>
""" + AUTHJS + """  <script>
  (function () {
    var q = new URLSearchParams(location.search), next = q.get('next') || '/members/';
    if (!/^\\/members\\//.test(next)) next = '/members/';
    var out = document.getElementById('mb-out'), form = document.getElementById('mb-form');
    function say(t, cls) { out.hidden = false; out.className = 'mb-msg ' + (cls || ''); out.innerHTML = t; }
    if (!SH_AUTH.ready) { form.hidden = true; document.getElementById('mb-intro').textContent = 'The members area is opening soon. Take the coaching questionnaire to be first in.'; return; }
    if (q.get('out')) say('You are logged out.');
    SH_AUTH.session().then(function (s) { if (s) location.replace(next); });
    try { var e = localStorage.getItem('sh-email'); if (e) document.getElementById('mb-email').value = e; } catch (x) {}
    form.addEventListener('submit', function (ev) {
      ev.preventDefault();
      var em = document.getElementById('mb-email').value.trim(), b = form.querySelector('button');
      b.disabled = true; b.textContent = 'Sending...';
      SH_AUTH.sendLink(em, { next: next }).then(function () {
        say('Check your email. Tap the link from Salvage Health on this device and you are in. It can take a minute, and check spam just in case.', 'ok');
        b.textContent = 'Link sent';
      }).catch(function (err) {
        b.disabled = false; b.textContent = 'Email me a login link';
        var msg = String(err && (err.message || err.code) || '');
        if (/signup|not found|not allowed|otp_disabled/i.test(msg)) say('I could not find a membership for that email. Membership is free when you finish the <a href="/coaching/qualify/">coaching questionnaire</a>.', 'err');
        else if (/rate|seconds/i.test(msg)) say('Too many tries. Wait a minute and try again.', 'err');
        else say('Something went wrong sending your link. Try again, or email hello@salvagehealth.com.', 'err');
      });
    });
  })();
  </script>
""" + FOOT
write("/members/login/", lp)

# ---- dashboard ---------------------------------------------------------------
dp = head("Members | Salvage Health", "Your Salvage Health members dashboard.", "/members/", NOINDEX + COACHCSS + MCSS) + topbar("members") + f"""  <main class="co mb">
    {mtop()}
    <h1 class="disp">Welcome<span id="mb-name"></span>. <em>Let's get to work.</em></h1>
    {mnav("home")}
    <section class="mb-sec" id="mb-nums" hidden>
      <h2>Your starting numbers</h2>
      <p>From your questionnaire. These get fine-tuned from your check-ins.</p>
      <div class="mb-tiles"><div class="hl"><b id="n-cal"></b><span>Daily calories</span></div><div><b id="n-p"></b><span>Protein</span></div><div><b id="n-c"></b><span>Carbs</span></div><div><b id="n-f"></b><span>Fat</span></div><div><b id="n-tdee"></b><span>Maintenance</span></div></div>
      <div class="mb-box" id="mb-rec" hidden><p><b style="color:var(--fg)">Recommended for you: <span id="n-rec"></span></b></p><p>I'll reach out to set up your free intro call. Want to move faster? Email <a href="mailto:hello@salvagehealth.com">hello@salvagehealth.com</a>.</p></div>
    </section>
    <section class="mb-sec" id="mb-none" hidden>
      <h2>Get your numbers</h2>
      <p>Take the <a href="/coaching/qualify/">2-minute questionnaire</a> and your calories, macros and coaching recommendation will show up here.</p>
    </section>
    <section class="mb-sec">
      <h2>Members library</h2>
      <div class="mb-cards">
        <a href="/members/bloodwork/"><small>Guide</small><b>Bloodwork guide</b><span>What to ask your doctor for, how to prep, and what each marker can tell you about a stall.</span></a>
        <a href="/members/peptides/"><small>Guide</small><b>Peptides 101</b><span>What peptides are, what's approved and what isn't, the red flags, and how to do it safely.</span></a>
        <a href="/kitchen/#foryou"><small>Kitchen</small><b>Meals for your numbers</b><span>Recipes matched to your goal and kitchen skill.</span></a>
        <a href="/start/kit/"><small>Starter Kit</small><b>Your 7-day plan</b><span>The first week, the grocery list and the cook-twice meal plan.</span></a>
      </div>
    </section>
    <p class="mb-disc">Salvage Health shares education, not medical advice. Talk to your doctor before you change how you eat, train or supplement.</p>
  </main>
""" + AUTHJS + """  <script>
  window.mbFill = function (m) {
    if (m.name) document.getElementById('mb-name').textContent = ', ' + String(m.name).split(' ')[0];
    if (m.calories) {
      document.getElementById('mb-nums').hidden = false;
      document.getElementById('n-cal').textContent = Number(m.calories).toLocaleString();
      document.getElementById('n-p').textContent = m.protein + 'g'; document.getElementById('n-c').textContent = m.carbs + 'g'; document.getElementById('n-f').textContent = m.fat + 'g';
      document.getElementById('n-tdee').textContent = Number(m.tdee).toLocaleString();
      if (m.recommendation) { document.getElementById('mb-rec').hidden = false; document.getElementById('n-rec').textContent = m.recommendation; }
    } else document.getElementById('mb-none').hidden = false;
  };
  </script>
""" + MEMBERJS + FOOT
write("/members/", dp)

# ---- bloodwork guide -----------------------------------------------------------
bp = head("Bloodwork guide | Salvage Health Members", "What to ask your doctor for and what it can tell you.", "/members/bloodwork/", NOINDEX + COACHCSS + MCSS) + topbar("members") + f"""  <main class="co mb">
    {mtop()}
    <h1 class="disp">Bloodwork <em>guide</em></h1>
    {mnav("labs")}
    <section class="mb-sec">
      <h2>Why bother?</h2>
      <p>The scale tells you one number. Your blood tells you what is happening underneath it: how your metabolism is running, how you handle sugar, whether your hormones and vitamins are working for you or against you. When someone is doing everything right and still stuck, this is often where the answer is.</p>
      <p>It also gives you a scoreboard that matters more than weight. Watching your A1C or triglycerides drop is proof your health is changing, not just your size.</p>
    </section>
    <section class="mb-sec">
      <h2>What to ask your doctor for</h2>
      <p>Bring this list to your appointment. Your doctor decides what makes sense for you, and may add or skip tests based on your history.</p>
      <h3>The basics</h3>
      <ul><li><b>CBC (complete blood count)</b>: red and white cells, platelets. Can flag anemia, which drains energy.</li>
      <li><b>CMP (comprehensive metabolic panel)</b>: blood sugar, kidney and liver function, electrolytes.</li>
      <li><b>Lipid panel</b>: total cholesterol, LDL, HDL and triglycerides.</li></ul>
      <h3>Blood sugar and insulin</h3>
      <ul><li><b>A1C</b>: your average blood sugar over about 3 months. This is the number that told me I was prediabetic.</li>
      <li><b>Fasting glucose</b> and <b>fasting insulin</b>: high insulin can show up years before blood sugar goes up, and it makes fat loss harder and cravings stronger.</li></ul>
      <h3>Thyroid</h3>
      <ul><li><b>TSH</b>, plus <b>free T4</b> and <b>free T3</b> if your doctor agrees. A slow thyroid can mean fatigue, feeling cold, and weight that will not move.</li></ul>
      <h3>Hormones</h3>
      <ul><li><b>Testosterone (total and free)</b> and <b>SHBG</b>, for men and women. Low levels hit energy, mood, drive, recovery and muscle.</li>
      <li><b>Estradiol</b>, and for women, other hormones your doctor recommends based on your cycle or menopause stage.</li></ul>
      <h3>Vitamins and iron</h3>
      <ul><li><b>Vitamin D</b>, <b>B12</b>, <b>ferritin</b> (iron stores) and <b>iron</b>. Low levels are common and can look exactly like a willpower problem.</li></ul>
    </section>
    <section class="mb-sec">
      <h2>How to prep</h2>
      <ul><li><b>Fast if asked.</b> Your doctor may want 8 to 12 hours of no food for glucose, insulin and lipids. Water is fine.</li>
      <li><b>Test in the morning.</b> Testosterone is highest early in the day, so morning draws give the most accurate read.</li>
      <li><b>Skip hard workouts and alcohol</b> the day before. Both can skew results.</li>
      <li><b>Tell your doctor about supplements.</b> Biotin in particular can throw off some lab tests, including thyroid.</li></ul>
    </section>
    <section class="mb-sec">
      <h2>How we use it in coaching</h2>
      <p>Share your results and what your doctor told you. I build your training, nutrition and recovery around what they found, and we retest every 3 to 6 months, or whenever your doctor recommends, so you can watch the numbers move.</p>
      <div class="mb-box">
        <p>Don't have a doctor, or want labs without the wait? Any provider works. One option is <a href="https://velacorehealth.com" target="_blank" rel="noopener">Velacore Health</a>, a telehealth company that connects you with licensed clinicians who can order labs.</p>
        <p style="color:var(--faint);font-size:13.5px">Disclosure: I founded Velacore Health. It is a separate company from Salvage Health and using it is never required.</p>
      </div>
    </section>
    <p class="mb-disc">I am not a doctor and this is not medical advice. I don't diagnose, treat or interpret lab results medically. Your doctor does that. Always follow their guidance about your results.</p>
  </main>
""" + AUTHJS + MEMBERJS + FOOT
write("/members/bloodwork/", bp)

# ---- peptides 101 --------------------------------------------------------------
pp = head("Peptides 101 | Salvage Health Members", "What peptides are, what is approved, the red flags and how to stay safe.", "/members/peptides/", NOINDEX + COACHCSS + MCSS) + topbar("members") + f"""  <main class="co mb">
    {mtop()}
    <h1 class="disp">Peptides <em>101</em></h1>
    {mnav("pep")}
    <section class="mb-sec">
      <h2>What peptides are</h2>
      <p>Peptides are short chains of amino acids, the same building blocks as protein. Your body makes thousands of them, and they act like messengers that tell cells what to do: release a hormone, signal fullness, start repair.</p>
      <p>The ones people talk about in fitness fall into two very different groups, and knowing the difference is the most important thing on this page.</p>
    </section>
    <section class="mb-sec">
      <h2>Two very different groups</h2>
      <h3>1. FDA-approved prescription medications</h3>
      <p>The GLP-1 medications, like semaglutide and tirzepatide, are the best-known example. They went through clinical trials, they are approved for specific uses, and they are prescribed and monitored by a licensed clinician. For the right person, they can be life-changing.</p>
      <h3>2. Unapproved "research" peptides</h3>
      <p>Many peptides you see online, including several popular for recovery or muscle, are not FDA-approved for human use. Some are sold labeled "for research only, not for human consumption." That label is a warning, not a loophole: there is no guarantee of what is in the vial, how pure it is, or how it was made.</p>
    </section>
    <section class="mb-sec">
      <h2>Red flags</h2>
      <ul><li>Sold without a prescription or a consultation with a licensed clinician.</li>
      <li>Labeled "research use only" or "not for human consumption."</li>
      <li>No pharmacy name, no batch testing, or prices that seem too good to be true.</li>
      <li>Big promises with no mention of side effects or who should not use it.</li>
      <li>Dosing advice from a forum, an influencer or a seller instead of a clinician.</li></ul>
    </section>
    <section class="mb-sec">
      <h2>How to do it the right way</h2>
      <ul><li><b>Start with labs and a real evaluation.</b> A clinician should know your health history and current numbers first.</li>
      <li><b>Prescription from a licensed clinician</b>, filled by a licensed pharmacy.</li>
      <li><b>Follow-up and monitoring</b>, with labs repeated over time.</li>
      <li><b>Keep the foundation.</b> Peptides do not replace protein, training, sleep and a calorie target. They work best on top of them, which is exactly what coaching builds.</li></ul>
      <div class="mb-box">
        <p>I share my own experience in <a href="/articles/my-peptide-journey/">My Peptide Journey</a>. If you want to explore peptide therapy, talk to your doctor or a licensed telehealth provider such as <a href="https://velacorehealth.com" target="_blank" rel="noopener">Velacore Health</a>.</p>
        <p style="color:var(--faint);font-size:13.5px">Disclosure: I founded Velacore Health. It is a separate company from Salvage Health and using it is never required for coaching.</p>
      </div>
    </section>
    <p class="mb-disc">This is education, not medical advice. I am not a doctor and I don't prescribe, sell or give dosing guidance for any medication or peptide. Talk to a licensed clinician about whether any treatment is right for you.</p>
  </main>
""" + AUTHJS + MEMBERJS + FOOT
write("/members/peptides/", pp)
